language: python

sudo: false

jobs:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
    env: RUN_CODESTYLE="true"

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - $HOME/.cache/pip
  pip: true

git:
  depth: 5

install:
  - pip install .[xgboost]

# command to run tests, e.g. python setup.py test
before_script:
  - ./codesytle.sh

# after_success:
#   - codecov
