language: python
dist: xenial
os: linux

jobs:
  include:
  - python: "3.6"
  - python: "3.7"
    env: USE_SINGULARITY="true"
  - python: "3.8"
    env: RUN_CODESTYLE="true"

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  pip

git:
  depth: 5

install:
  - chmod +x ci_scripts/install.sh && source ./ci_scripts/install.sh

before_script:
  - chmod +x ci_scripts/codestyle.sh && source ./ci_scripts/codestyle.sh

script:
  - chmod +x ci_scripts/script.sh && source ./ci_scripts/script.sh