language: python

dist: xenial

os: linux


jobs:
  include:
  - python: "3.6"
  - python: "3.7"
    env:
    - USE_SINGULARITY="true"
    - GOROOT=/usr/local/go/bin
    - GOPATH=~/.go/bin
    - PATH=$PATH:$GOROOT:$GOPATH
  - python: "3.8"
    env: RUN_CODESTYLE="true"

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  pip

git:
  depth: 5

install:
  - chmod +x ci_scripts/install.sh && source ./ci_scripts/install.sh $USE_SINGULARITY

# command to run tests, e.g. python setup.py test
before_script:
  - chmod +x ci_scripts/codestyle.sh && source ./ci_scripts/codestyle.sh $RUN_CODESTYLE

# after_success:
#   - codecov
